# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald
  theme_day: minimal
  theme_night: minimal

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "My Personal Website"
    twitter: ""
  analytics:
    google_analytics: "G-2EK9NM0D2P"
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Divyansh Tripathi"

# Site footer
footer:
  copyright:
    notice: "Â© {year} Divyansh Tripathi. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
